// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizWhizAPI.Data;

#nullable disable

namespace QuizWhizAPI.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20240805070949_initial Migration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.CreatedQuiz", b =>
                {
                    b.Property<int>("CreatedQuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreatedQuizId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CreatedQuizId");

                    b.HasIndex("UserId");

                    b.ToTable("CreatedQuizzes");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CreatedQuizId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CreatedQuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.TakeQuiz", b =>
                {
                    b.Property<int>("TakeQuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakeQuizId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedQuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TakeQuizId");

                    b.HasIndex("CreatedQuizId");

                    b.HasIndex("UserId");

                    b.ToTable("TakeQuizzes");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.CreatedQuiz", b =>
                {
                    b.HasOne("QuizWhizAPI.Models.Entities.User", "CreatedBy")
                        .WithMany("CreatedQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.Question", b =>
                {
                    b.HasOne("QuizWhizAPI.Models.Entities.CreatedQuiz", "CreatedQuiz")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedQuiz");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.TakeQuiz", b =>
                {
                    b.HasOne("QuizWhizAPI.Models.Entities.CreatedQuiz", "CreatedQuiz")
                        .WithMany("TakeQuizzes")
                        .HasForeignKey("CreatedQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizWhizAPI.Models.Entities.User", "TakenBy")
                        .WithMany("TakeQuizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedQuiz");

                    b.Navigation("TakenBy");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.CreatedQuiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TakeQuizzes");
                });

            modelBuilder.Entity("QuizWhizAPI.Models.Entities.User", b =>
                {
                    b.Navigation("CreatedQuizzes");

                    b.Navigation("TakeQuizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
